<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginKeywordTable extends Doctrine_Table
{
	public function createQuery($alias = '')
	{
		//By default, collection is ordered by length descending.  This prevents word overlap
		// ex: 'my word' will match before 'word'.  More "specific" Keywords match first
		$q = parent::createQuery($alias);
		$q->select('*, LENGTH(name) as length')->orderBy('length DESC');
		return $q;
	}
	public function findAllAsArray()
	{
		return $this->collectionToArray($this->findAll());
	}
	public function collectionToArray($collection)
	{
		$arr = array();
		foreach ($collection as $keyword) 
		{
			$arr[] = $keyword->getName();
		}
		return $arr;
	}
}