# MetaData:
#   columns:
#     seo_page_id:
#       type:         integer
#     title:  string(255)
#     description:  clob
#     keywords:   string(255)
#   relations:
#     SeoPage:
#       type:         one
#       foreignType:  one    