SeoPage:
  actAs: [Timestampable]
  columns:
    url:    string(255)
    title:  string(255)
    description:  clob
    underride_meta_data:
      type:     boolean
      default:  false
    exclude_from_sitemap:
      type:     boolean
      default:  false
    keywords:   string(255)
    priority:    
      type:         decimal
      default:      .5
    changeFreq:  
      type:         enum
      values:       [always,hourly,daily,weekly,monthly,yearly,never]
      default:      weekly