# SitemapItem:
#   actAs:  [Timestampable]
#   columns:
#     seo_page_id:
#       type:         integer
#     priority:    
#       type:         decimal
#       default:      .5
#     changeFreq:  
#       type:         enum
#       values:       [always,hourly,daily,weekly,monthly,yearly,never]
#       default:      weekly
#   relations:
#     SeoPage:
#       type:         one
#       foreignType:  one
#       